steps:
- name: 'ubuntu'
  args: ['bash', './myscript.sh']
  env:
  - '_RANDOM_VALUE=$_RANDOM_VALUE'
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"